# Spring Boot configuration
spring:
  profiles:
    active: development

# Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://hbs-db.cyew5qz80jan.us-east-2.rds.amazonaws.com/postgres
    username: hitriton
    password: CjjSxdy11KUs2ZqYkKjB
    
      # JPA properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    
    # Server configuration
server:
  port: 
   8080 #set your port